baseURL = 'https://jaeho-lee.github.io/'
languageCode = 'en-us'
title = "Jaeho Lee"
theme = "risotto"
paginate = 3
DefaultContentLanguage = "en"
# enableInlineShortcodes = true
# ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "main"

[params]

[params.theme]
palette = "custombox"
mode = "light-mode"

# Sidebar: about/bio
[params.about]
title = "Jaeho Lee"
description = """ML researcher who also teaches.
(firstname).(lastname) (at) postech.ac.kr
"""
#logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:jaeho.lee@postech.ac.kr"

[[params.socialLinks]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/jaeho_lee_"


#[[params.socialLinks]]
#icon = "ai ai-google-scholar"
#title = "Google Scholar"
#url = "https://scholar.google.com/citations?hl=en&user=t91zoQMAAAAJ&view_op=list_works&sortby=pubdate"

[menu]

[[menu.main]]
identifier = "papers"
name = "Papers"
url = "/papers/"
weight = 1

[[menu.main]]
identifier = "withme"
name = "Work with me?"
url = "/withme/"
weight = 2

[[menu.main]]
identifier = "misc"
name = "misc."
url = "/misc/"
weight = 3


# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true
